# Generated by Django 3.0.8 on 2020-07-18 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SalesOrders',
            new_name='SalesOrder',
        ),
    ]
