# Generated by Django 3.0.8 on 2020-07-20 23:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='имя')),
                ('birthday', models.DateTimeField(verbose_name='дата публикации')),
                ('account', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
