# Generated by Django 3.0.8 on 2020-07-20 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='birthday',
            field=models.DateTimeField(verbose_name='день рождения'),
        ),
    ]
